#!/usr/bin/env bash
#displays information about sub domains
function check_record {
  local domain=$1
  local subdomain=$2

  if [[ -z "$subdomain" ]]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
  else
    subdomains=("$subdomain")
  fi

  for sub in "${subdomains[@]}"; do
    record_type=$(dig $sub.$domain | grep -A1 'ANSWER SECTION' | awk '{print $4}' | tail -1)
    destination=$(dig $sub.$domain | grep -A1 'ANSWER SECTION' | awk '{print $5}' | tail -1)

    echo "The subdomain $sub is a $record_type record and points to $destination"
  done
}

check_record "$1" "$2"
