#!/usr/bin/env bash
# Redirects to another page

sudo apt-get update
sudo apt-get install -y nginx

sudo mkdir -p /var/www/root
sudo echo "Hello World!" | sudo tee /var/www/root/index.html

echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/root;
	index index.html index.htm;

	location /redirect_me {
		return 301 https://www.example.com;
	}
}" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart
