#!/usr/bin/env bash
# 404 redirection page

sudo apt-get update
sudo apt-get install -y nginx

sudo mkdir -p /var/www/root
sudo echo "Hello World!" | sudo tee /var/www/root/index.html
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/root/404.html

sudo echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/root;
	index index.html index.htm;
	
	location /redirect_me {
		return 301 https://www.example.com;
	}

	error_page 404 /404.html;
	location /404 {
		root /var/www/root;
		internal;
	}
}" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart
